### PR TITLE
Upgrade pulumi sdk packages

### PR DESCRIPTION
**Pull request by sklarsa**
I'm developing a project that is using go 1.23.3 and `github.com/pulumi/pulumi/sdk/v3 v3.142.0`. When trying to compile a provider binary using the same module, I get compilation errors:

```
# github.com/pulumi/pulumi/pkg/v3/workspace
../../../go/pkg/mod/github.com/pulumi/pulumi/pkg/v3@v3.134.0/workspace/plugin.go:65:29: not enough arguments in call to pluginSpec.GetLatestVersion
	have ()
	want ("context".Context)
../../../go/pkg/mod/github.com/pulumi/pulumi/pkg/v3@v3.134.0/workspace/plugin.go:83:71: not enough arguments in call to workspace.DownloadToFile
	have ("github.com/pulumi/pulumi/sdk/v3/go/common/workspace".PluginSpec, func(stream "io".ReadCloser, size int64) "io".ReadCloser, func(err error, attempt int, limit int, delay time.Duration))
	want ("context".Context, "github.com/pulumi/pulumi/sdk/v3/go/common/workspace".PluginSpec, func(stream "io".ReadCloser, size int64) "io".ReadCloser, func(err error, attempt int, limit int, delay time.Duration))
```

### CODE REVIEW

**Review by iwahbe — CHANGES_REQUESTED** [review]
Hi @sklarsa. Thanks for opening a PR.

This library supports all currently supported go versions (1.22 & 1.23). I'd be happy to take the version bump on `github.com/pulumi/pulumi/{pkg,sdk}/v3`, we will defer updating the Go version until Go 1.24 comes out.

**Comment by mjeffryes** [comment]
@sklarsa See the test failures: looks like a `go mod tidy` is still required

**Comment by sklarsa** [comment]
handled here: https://github.com/pulumi/pulumi-go-provider/commit/0133e9074416d827583c663de7c82d835a9a2bab

**Comment by sklarsa** [comment]
Ah I need to rerun the `go mod tidy`. Can dependabot do this for me?

**Review by iwahbe — APPROVED** [review]
Thanks for updating here!

**Pull request merged**
